### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ayaahmed281** [XAM-Consulting/SlideOverKit#50] opened 2017-10-18 15:02 UTC
first thanks for amazing plugin for me it was very helpful
second i want ask about thing and wish you help me
 i used  quick menu from bottom view and when i select row from it it will show another view have another quick menu from bottom 

i need it to be opened before sliding then start slide down +up 

please how can makequick menu from bottom 
 on first render open  then start use slide functionalty?

**Comment by jessejiang0214** [comment] 2017-10-23 00:06
So you want to use two SlideMenuView in the same page? This feature is not allowed by design.

**Comment by ayaahmed281** [comment] 2017-10-23 04:55
ok thanks for replay :) i use slide Menu view and add drag button height and it act well as quickMenu but need ask how can i use access functionality of showSlide from page to view when click on view item open another slideMenu but be open ,

i do it but when click on first view item appear another view with another slide menu but closed when click on button show menu it open but i need be opend firstly

**Comment by jessejiang0214** [comment] 2017-10-25 03:08
I think you can use [MessageCenter](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/messaging-center/) to send message between two pages and open the menu in another page

**Comment by ayaahmed281** [comment] 2017-10-25 08:40
but in need change between views in same page can you help please ?

**Comment by jessejiang0214** [comment] 2017-10-25 22:46
What do you mean between views? If your views mean two SlideMenuView, as I told you, you cannot do that. If your views are one SlideMenuView and other one is normal view in Xamairn Forms. You can use MessageCenter and Binding to do that, and that is a basic thing in Xamarin.Forms, that is not a bug or feature in SlideOverKit.  

So I close this issue.
Thanks,

**Closed by jessejiang0214** 2017-10-25 22:46 UTC

**Comment by ayaahmed281** [comment] 2017-10-26 08:09
yes sure its  not i a bug or feature in SlideOverKit.  thanks for replay
